### ISSUE TITLE
Polya-Urn Version 2 solution has a typo let's please discuss!

### ISSUE THREAD

**Issue by arcolombo** [PM520-Spring2022/Solutions#1]
@pmarjora  @huoying831 
First off, the object-oriented solution is rad.  But there is a typo i think in the if/else solution.
 The logic is to sample the probability space (0,1) and if p< w/(w+n)  then this is the probability that the black ball is selected.
 
 So the initial configuration of the Urn has 2 balls.   so the probability of drawing black is 1/2  not 1/3.   
 So for example the urn has 1 Black, 1 Red ball.  drawing the first iteration the below command is the error:

"p<UrnThings$MutationBallWeight/(UrnThings$MutationBallWeight+Nballs"  
 this is essentially  p<1/(1+2) = 1/3   which is not true.

 if (UrnThings$UseMutationBall==1){   # this is not actually represented by a ball in the urn
                p<-runif(1,0,1)
                if (p<UrnThings$MutationBallWeight/(UrnThings$MutationBallWeight+Nballs)){
                    #  we picked the black ball
                    WhichToCopy<-0    # O codes the black ball
                }else{
                    WhichToCopy<-UrnThings$DrawFromUrn(Nballs)
                }
            }else{
                WhichToCopy<-UrnThings$DrawFromUrn(Nballs)
            }

**Comment by arcolombo** [comment]
@pmarjora   
Note that the Nballs is assigned to 2 (it is the starting configuration)
Nballs<-length(UrnThings$StartingConfiguration)

so this command : p <UrnThings$MutationBallWeight/(UrnThings$MutationBallWeight+Nballs  is equivalent (at the first iteration) to be p<1/3   which is not true.

**Comment by pmarjora** [comment]
Thanks for the heads-up. Let me look into that to see what I find. I have another solution somewhere that is not object-oriented, so I'll try to find that one as well.

**Comment by arcolombo** [comment]
this answer may even out during the trials,  but if you trace it for the first few draws,  the p<(w/(w+n)) might need a second look based on the lecture slides.   (i.e.  the initial draw for black is 1/2  not 1/3 and this (who knows) may affect the process.    #seekTruth

**Comment by pmarjora** [comment]
I found my other version of the code. It gives the following mean number of colors for weights of 1,2,3,4 and 5:
4.0246 6.5208 8.5476 10.259 11.8468
So I think you have indeed found a big! Thanks for that!

**Comment by pmarjora** [comment]
I actually think the error was elsewhere. I count the number of balls not including the black ball, so the line you pointed out was correct. But I was picking the ball whose color would change incorrectly on line 98.
I have now fixed that and will upload a corrected version which gives essentially the same numbers as those I give above.

Thanks for your help finding this error!
